#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-insuficiencia
spec:
  selector:
    matchLabels:
      app: mi-muerte
  replicas: 1
  template:
    metadata:
      labels:
        app: mi-muerte
    spec:
      containers:
      - name: mi-contenedor
        image: docker.io/112334emi/fast:latest
        ports:
        - containerPort: 80

      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mi-muerte
  name: mi-muerte
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mi-muerte
  type: LoadBalancer

